# Generated by Django 3.2.9 on 2021-11-15 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_body'),
        ('blog', '0006_comment'),
    ]

    operations = [
    ]
